[project]
org-name = "ldclakmal"
version = "1.0.1"
license = ["Apache-2.0"]
authors = ["Chanaka Lakmal"]
repository = "https://github.com/ldclakmal/module-twitter"
keywords = ["ballerina", "twitter", "connector", "integration"]
