[package]
org = "ldclakmal"
name = "twitter"
version = "2.0.6"
authors = ["Chanaka Lakmal"]
repository = "https://github.com/ldclakmal/ballerina-twitter-module"
license = ["Apache-2.0"]
keywords = ["ballerina", "twitter", "connector", "twitter developer"]
