name: Deployment

on:
    release:
        types: [published]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      build -a -c
              env:
                  CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
                  CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
                  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      push -a
              env:
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
